{
 "title": "Docker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values(container_uptime_seconds,host_name)"
    }
   },
   {
    "name": "docker_name",
    "label": "Docker Name",
    "query": {
     "query": "label_values(container_uptime_seconds{host_name=\"$host_name\"},container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_uptime_seconds{container_name=\"$docker_name\", host_name=\"$host_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_restarts_total{container_name=\"$docker_name\", host_name=\"$host_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Image",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<div style=\"\n  font-size:36px;\n  font-weight:bold;\n  padding:20px;\n\">\n  {{ container_image_name }}\n</div>"
   },
   "targets": [
    {
     "expr": "container_uptime_seconds{host_name=\"$host_name\", container_name=\"$docker_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_percent_ratio{container_name=\"$docker_name\", host_name=\"$host_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_total_bytes{container_name=\"$docker_name\", host_name=\"$host_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{container_name=\"$docker_name\", host_name=\"$host_name\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_io_usage_rx_bytes_total{container_name=\"$docker_name\", host_name=\"$host_name\"}[$__rate_interval])",
     "legendFormat": "{{container_name}} {{interface}} recv"
    },
    {
     "expr": "rate(container_network_io_usage_tx_bytes_total{container_name=\"$docker_name\", host_name=\"$host_name\"}[$__rate_interval])",
     "legendFormat": "{{container_name}} {{interface}} send"
    }
   ]
  }
 ]
}