{
 "title": "HTTP Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BlackBox Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "up{instance=\"$endpoint\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Probe Result",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "probe_success{instance=\"$endpoint\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"$endpoint\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$endpoint\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Body Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_uncompressed_body_length{instance=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Redirects",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{instance=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": {
    "content": "<div style=\"\n  font-size:36px;\n  font-weight:bold;\n  padding:20px;\n\">\n  <p>{{ version }}</p>\n</div>"
   },
   "targets": [
    { "expr": "probe_tls_version_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cipher",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "options": {
    "content": "<div style=\"\n  font-size:36px;\n  font-weight:bold;\n  padding:20px;\n\">\n  <p>{{ cipher }}</p>\n</div>"
   },
   "targets": [
    { "expr": "probe_tls_cipher_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Chain Cert Expirey",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_last_chain_expiry_timestamp_seconds{instance=\"$endpoint\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earliest Cert Expiry",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{instance=\"$endpoint\"} - time())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate Fingerprint / Serialnumber",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"\n  font-size:36px;\n  font-weight:bold;\n  padding:20px;\n\">\n  <p>Fingerprint: {{ fingerprint_sha256 }}</p>\n  <p>Serialnumber: {{serialnumber}}</p>\n</div>"
   },
   "targets": [
    { "expr": "probe_ssl_last_chain_info", "legendFormat": "__auto" }
   ]
  }
 ]
}