{
 "title": "Operating System Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "host_name",
    "query": {
     "query": "label_values(system_cpu_load_average_1m,host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_load_average_1m{host_name=\"$host_name\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Load 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_load_average_5m{host_name=\"$host_name\"}",
     "legendFormat": "Load 5m"
    }
   ]
  },
  {
   "title": "Load 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_load_average_15m{host_name=\"$host_name\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(system_processes_count{host_name=\"$host_name\"})",
     "legendFormat": "Processes"
    },
    {
     "expr": "system_processes_count{host_name=\"$host_name\", status=\"zombies\"}",
     "legendFormat": "Zombies"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_network_connections{host_name=\"$host_name\", state=~\"ESTABLISHED|LISTEN|SYN_RECV|SYN_SENT\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(system_cpu_time_seconds_total{host_name=\"$host_name\", state=\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(state) (rate(system_cpu_time_seconds_total{host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(system_memory_usage_bytes{host_name=\"$host_name\", state=~\"used|slab_unreclaimable\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_bytes_total{host_name=\"$host_name\", device!~\"^loop[0-9]+(p[0-9]+)?$\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(system_disk_operations_total{host_name=\"$host_name\", device!~\"^loop[0-9]+(p[0-9]+)?$\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{host_name=\"$host_name\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "Filesystem Inode Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mountpoint) (system_filesystem_inodes_usage{host_name=\"$host_name\", device!~\"^/dev/loop[0-9]+(p[0-9]+)?$\", state=\"used\"}) / (clamp_min(sum by(mountpoint) (system_filesystem_inodes_usage{host_name=\"$host_name\", device!~\"^/dev/loop[0-9]+(p[0-9]+)?$\"}), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mountpoint) (system_filesystem_usage_bytes{host_name=\"$host_name\", device!~\"^/dev/loop[0-9]+(p[0-9]+)?$\", state=\"used\"})\n/\nsum by (mountpoint) (system_filesystem_usage_bytes{host_name=\"$host_name\", device!~\"^/dev/loop[0-9]+(p[0-9]+)?$\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Pending Disk Operations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_disk_pending_operations{host_name=\"$host_name\", device!~\"^loop[0-9]+(p[0-9]+)?$\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(system_disk_operation_time_seconds_total{host_name=\"$host_name\", device!~\"^loop[0-9]+(p[0-9]+)?$\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "Weighted IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(system_disk_weighted_io_time_seconds_total{host_name=\"$host_name\", device!~\"^loop[0-9]+(p[0-9]+)?$\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}